# Generated by Django 3.1.1 on 2020-09-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("start_price", models.IntegerField(verbose_name="Начальная цена")),
                (
                    "price_step",
                    models.SmallIntegerField(default=100, verbose_name="Шаг цены"),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(verbose_name="Дата завершения аукциона"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={"verbose_name": "аукцион", "verbose_name_plural": "аукционы",},
        ),
    ]
